import type { ChallengeDef } from "./types";

export const CHALLENGES: ChallengeDef[] = [
  {
    id: "three_day_gentle_start",
    title: "3-Day Gentle Start",
    duration_days: 3,
    category: "starter",
    daily_structure: ["Warm water on waking", "Fruit before lunch", "Dinner before 7:30 pm"],
    badge_id: "gentle_starter",
    garden_unlock: "tulsi",
    notification_example: "Day 1 of your Gentle Start: just a glass of warm water. That's all today.",
    next_recommended: "7-Day Satvic Breakfast Challenge",
  },
  {
    id: "seven_day_satvic_breakfast",
    title: "7-Day Satvic Breakfast",
    duration_days: 7,
    category: "starter",
    daily_structure: ["Fruit plate", "Soaked almonds + fruit", "Smoothie", "Soaked dates + fruit", "Banana + chia water", "Mixed fruit salad", "Choose your favourite"],
    badge_id: "recipe_explorer",
    garden_unlock: "lemon",
    notification_example: "Tomorrow morning: a small fruit plate before tea/coffee.",
    next_recommended: "7-Day Light Dinner Challenge",
  },
  {
    id: "seven_day_light_dinner",
    title: "7-Day Light Dinner",
    duration_days: 7,
    category: "starter",
    target_path: "digestion_support",
    daily_structure: ["Moong khichdi", "Vegetable soup", "Stewed seasonal veg + jowar roti", "Khichdi again", "Light dal + rice", "Soup + roti", "Free Satvic choice"],
    badge_id: "early_dinner_explorer",
    garden_unlock: "jowar",
    notification_example: "Day 4 of light dinners. Tonight: vegetable soup or moong khichdi.",
    next_recommended: "21-Day Satvic Reset",
  },
  {
    id: "seven_day_no_packaged_snack",
    title: "7-Day No Packaged Snack",
    duration_days: 7,
    category: "family",
    daily_structure: ["Fruit", "Roasted chana", "Soaked nuts", "Coconut sweet", "Sprouts chat", "Homemade laddoo", "Free Satvic snack"],
    badge_id: "family_wellness_starter",
    garden_unlock: "tree_family",
    notification_example: "Today's swap: roasted chana instead of packaged chips.",
    next_recommended: "Family Satvic Week",
  },
  {
    id: "summer_cooling",
    title: "Summer Cooling Challenge",
    duration_days: 7,
    category: "seasonal",
    daily_structure: ["Coconut water", "Sabja-lemon sip", "Watermelon-mint juice", "Buttermilk", "Cucumber sip", "Sattu drink", "Coconut + mint cooler"],
    badge_id: "seasonal_eater",
    garden_unlock: "mango",
    notification_example: "Hot day in your city — try a coconut water before any packaged juice.",
    next_recommended: "Light Dinner Challenge",
  },
  {
    id: "monsoon_digestion",
    title: "Monsoon Digestion Challenge",
    duration_days: 7,
    category: "seasonal",
    daily_structure: ["Tulsi-ginger tea", "Cooked greens", "Warm khichdi", "Light soup", "No raw salad", "Spiced buttermilk", "Free choice"],
    badge_id: "early_dinner_explorer",
    garden_unlock: "lotus",
    notification_example: "Rainy week — skip raw salads tonight. Cooked greens digest easier.",
    next_recommended: "21-Day Satvic Reset",
  },
  {
    id: "festival_reset",
    title: "Festival Reset (5 days)",
    duration_days: 3,
    category: "festival",
    daily_structure: ["Fruit + warm water", "Khichdi dinner", "Walk + hydration"],
    badge_id: "mindful_eater",
    garden_unlock: "marigold",
    notification_example: "Post-festival reset: tomorrow starts with fruit + warm water.",
    next_recommended: "7-Day Satvic Breakfast",
  },
  {
    id: "family_satvic_week",
    title: "Family Satvic Week",
    duration_days: 7,
    category: "family",
    daily_structure: ["One swap", "Jowar roti", "Family fruit plate", "Screen-free dinner", "Tiffin swap", "Cook together", "Reflect together"],
    badge_id: "family_wellness_starter",
    garden_unlock: "tree_family",
    notification_example: "Family Satvic Week — tonight, one shared swap at dinner.",
    next_recommended: "Kids' Tiffin Transformation",
  },
  {
    id: "twenty_one_day_satvic_reset",
    title: "21-Day Satvic Reset",
    duration_days: 21,
    category: "starter",
    daily_structure: ["Week 1 mornings", "Week 2 meals", "Week 3 evenings"],
    badge_id: "seven_day_rhythm",
    garden_unlock: "pomegranate",
    notification_example: "Day 14 of your 21-Day Satvic Reset — beautifully steady.",
    next_recommended: "Deep Satvic Practice",
  },
];

export const CHALLENGE_MAP: Record<string, ChallengeDef> = Object.fromEntries(
  CHALLENGES.map((c) => [c.id, c]),
);
