import type { PathDef, PathId, QuizAnswers } from "./types";

const day = (
  day_index: number,
  title: string,
  lesson_title: string,
  lesson_body: string,
  estimated_minutes: number,
  next_preview: string,
  recipe_id?: string,
) => ({ day_index, title, lesson_title, lesson_body, estimated_minutes, next_preview, recipe_id });

export const PATHS: Record<PathId, PathDef> = {
  gentle_beginner: {
    id: "gentle_beginner",
    name: "Gentle Beginner",
    emoji: "🌱",
    tagline: "One small habit at a time.",
    rationale:
      "You're new to Satvic — and that's the most beautiful place to start. We'll go gently, with one tiny step a day. You can't do this wrong.",
    emotional_tone: "Reassuring, slow, 'you can't do this wrong.'",
    starter_badge: "gentle_starter",
    starter_plant: "tulsi",
    example_notification: "Your first Satvic step today: one glass of warm water. That's all.",
    days: [
      day(1, "Drink one glass of warm water on waking", "Why warm water?",
        "Warm water gently wakes the digestive system and supports natural elimination. No lemon needed on day one. Just a small glass, warm to the touch, before tea or coffee.", 5,
        "Tomorrow: a fruit before lunch."),
      day(2, "Eat one fruit before lunch", "Fruits before meals",
        "Eating fresh fruit on a fairly empty stomach helps digestion and prevents the heaviness of fruits-after-meals. Choose any seasonal fruit you love.", 5,
        "Tomorrow: dinner before 7:30 pm.",
        "fruit_plate"),
      day(3, "Finish dinner before 7:30 pm", "Early dinner = restful sleep",
        "An earlier, lighter dinner gives the body a longer rest from digestion overnight. Most people notice better sleep within 2–3 days.", 15,
        "Tomorrow: a 5-minute mindful sip of warm water before bed."),
      day(4, "5-minute mindful warm water before bed", "Pause before sleeping",
        "A few sips of warm water, savoured slowly, is a tiny ritual of pause. It tells the body 'we are slowing down now.'", 5,
        "Tomorrow: soak almonds tonight."),
      day(5, "Soak 5 almonds tonight", "Soaking unlocks goodness",
        "Soaked almonds are gentler on digestion and easier for the body to absorb. Five is plenty.", 2,
        "Tomorrow: eat your soaked almonds with breakfast."),
      day(6, "Eat your soaked almonds with breakfast", "A Satvic breakfast in 2 minutes",
        "Peel and eat your soaked almonds with one fruit. That's a complete Satvic breakfast — calm, nourishing, and 2 minutes long.", 5,
        "Tomorrow: walk for 10 minutes after dinner.",
        "soaked_almonds_breakfast"),
      day(7, "Walk for 10 minutes after dinner", "A small evening walk",
        "A gentle stroll after dinner helps digestion and unwinds the mind. No counting steps. Just walk softly.", 10,
        "You've completed your first Satvic week 🌿"),
    ],
  },

  digestion_support: {
    id: "digestion_support",
    name: "Digestion Support",
    emoji: "🌙",
    tagline: "Calm the gut, gently.",
    rationale:
      "Many in our community find these gentle habits soothing. This is general lifestyle guidance, not medical advice — please consult a doctor for chronic issues.",
    emotional_tone: "Calm, practical, with a soft disclaimer.",
    starter_badge: "early_dinner_explorer",
    starter_plant: "mint",
    example_notification: "Tonight, try dinner by 7:30 — your gut rests better that way.",
    days: [
      day(1, "Warm water through the morning", "Warmth is kind to digestion",
        "Cold water can shock the system. Warm sips — like a thermos by your side — calm the gut.", 5, "Tomorrow: light khichdi for dinner."),
      day(2, "Light moong khichdi for dinner", "The Satvic comfort meal",
        "Moong khichdi is the gentlest dinner — easy to digest, deeply nourishing.", 20, "Tomorrow: chew 20 times at one meal.",
        "moong_khichdi"),
      day(3, "Chew each bite 20 times at one meal", "Chewing is digestion",
        "Most digestion problems begin in the mouth. Chewing fully takes pressure off the gut.", 15, "Tomorrow: ginger-jeera tea after lunch."),
      day(4, "Ginger-jeera tea after lunch", "A soft post-meal sip",
        "Half a cup of warm ginger-jeera water aids digestion and reduces bloating.", 5, "Tomorrow: dinner before 7:30 pm.",
        "ginger_jeera_tea"),
      day(5, "Dinner before 7:30 pm", "Early light dinners",
        "Notice how morning feels lighter when dinner is earlier.", 15, "Tomorrow: rest day — repeat any favorite."),
      day(6, "Repeat your favorite habit from the week", "Listening is a skill",
        "Pick the one habit that felt best. Repeat it kindly.", 10, "Tomorrow: morning mindful breathing for 3 minutes."),
      day(7, "3-min mindful breathing in the morning", "Breath = digestion's friend",
        "Slow breathing in the morning gently primes the gut for the day.", 3, "Beautifully done. 🌿"),
    ],
  },

  weight_balance: {
    id: "weight_balance",
    name: "Weight Balance",
    emoji: "🍃",
    tagline: "Energy first, not the scale.",
    rationale:
      "We don't count calories here. Weight balance follows naturally from steady habits and energy. Move at your pace.",
    emotional_tone: "Body-positive, non-restrictive, energy-focused.",
    starter_badge: "mindful_eater",
    starter_plant: "lemon",
    example_notification: "Today's gentle step: a fruit plate before breakfast. No counting. Just colours.",
    days: [
      day(1, "Fruit plate before breakfast", "Fruits in the morning",
        "Eating a bowl of fresh fruits before breakfast adds fibre, water, and gentle energy.", 5, "Tomorrow: warm water before lunch.",
        "morning_fruit_plate"),
      day(2, "Warm water 15 min before lunch", "A small reset before meals",
        "A glass of warm water before a meal calms the appetite and aids digestion.", 5, "Tomorrow: 10-min walk after dinner."),
      day(3, "10-minute walk after dinner", "The most underrated habit",
        "A slow stroll after dinner gently supports balance and sleep.", 10, "Tomorrow: replace one packaged snack."),
      day(4, "Replace one packaged snack today", "Tiny swaps add up",
        "Pick one packaged snack and swap it for a fruit, soaked nuts, or roasted chana.", 5, "Tomorrow: chew slowly at lunch."),
      day(5, "Chew slowly at one meal", "Mindful eating",
        "Slow chewing helps the body register fullness gently.", 10, "Tomorrow: light dinner by 7:30 pm."),
      day(6, "Light dinner by 7:30 pm", "Earlier is gentler",
        "Light dinners support metabolism without restriction.", 15, "Tomorrow: notice your energy at 4 pm."),
      day(7, "Notice your 4 pm energy today", "Energy is the real metric",
        "Don't weigh yourself. Notice your afternoon energy instead.", 2, "Beautifully done 🌿"),
    ],
  },

  family_satvic: {
    id: "family_satvic",
    name: "Family Satvic",
    emoji: "👨‍👩‍👧",
    tagline: "Small swaps the family will love.",
    rationale:
      "Family change is gentle change. We start with one swap at a time — small, tasty, and family-friendly.",
    emotional_tone: "Inclusive, slow swaps.",
    starter_badge: "family_wellness_starter",
    starter_plant: "tree_family",
    example_notification: "Tonight, swap maida roti for one jowar roti at the table. Keep it small.",
    days: [
      day(1, "Swap one packaged snack at home", "One small swap",
        "Pick the family's most-eaten packaged snack and put a Satvic alternative beside it.", 10, "Tomorrow: cook a soft jowar roti.",),
      day(2, "One soft jowar roti at dinner", "Whole grains, gentle taste",
        "Jowar rotis are easy to start with — soft, neutral, kid-friendly.", 15, "Tomorrow: a family fruit plate.",
        "soft_jowar_roti"),
      day(3, "Family fruit plate before dinner", "Fruits as a family ritual",
        "Place one shared fruit plate at the table 15 minutes before dinner.", 5, "Tomorrow: a 5-min screen-free dinner."),
      day(4, "Screen-free family dinner for 5 minutes", "Even 5 minutes counts",
        "Begin with five minutes. Build from there.", 5, "Tomorrow: a tiffin swap."),
      day(5, "One Satvic tiffin item today", "Kids' tiffin idea",
        "Soft chila, fruit pieces, or a homemade laddoo — one Satvic item in the lunchbox.", 15, "Tomorrow: morning warm water together.",
        "satvic_tiffin_chila"),
      day(6, "Morning warm water together", "Family ritual",
        "Pour glasses for everyone. Sip together.", 5, "Tomorrow: cook one Satvic recipe together."),
      day(7, "Cook a Satvic recipe together", "Together is the secret",
        "Pick anyone in the family and cook one dish together. That's the entire goal.", 30, "Beautifully done as a family 🌿"),
    ],
  },

  seasonal_wellness: {
    id: "seasonal_wellness",
    name: "Seasonal Wellness",
    emoji: "☀️",
    tagline: "Eat with the season.",
    rationale:
      "The body listens to the season. We'll align tiny habits with what your body needs this ritu.",
    emotional_tone: "Rooted, traditional.",
    starter_badge: "seasonal_eater",
    starter_plant: "marigold",
    example_notification: "The afternoons are heating up. Try a sabja-lemon cooler today.",
    days: [
      day(1, "One seasonal fruit today", "What's in season here?",
        "Look around the local market for the fruit most in season — that's the body's friend right now.", 5, "Tomorrow: a seasonal drink."),
      day(2, "A seasonal cooling/warming drink", "Match the season",
        "Summer → sabja-lemon water. Winter → ginger-jaggery sip. Trust the season.", 5, "Tomorrow: an earlier sunrise.",
        "seasonal_cooler"),
      day(3, "Wake 15 minutes earlier", "Sun-aligned rhythm",
        "Try waking 15 minutes earlier with natural light if possible.", 5, "Tomorrow: a seasonal vegetable at dinner."),
      day(4, "A seasonal vegetable at dinner", "Eat the ritu",
        "Cook with one local, seasonal vegetable at dinner.", 20, "Tomorrow: an oil suited to the season."),
      day(5, "Switch to a seasonal oil for one meal", "Cooling vs warming oils",
        "Summer → coconut/ghee. Winter → sesame.", 10, "Tomorrow: a seasonal herb today."),
      day(6, "Use one seasonal herb today", "Herbs are seasonal",
        "Tulsi, mint, coriander — pick one and add to a meal.", 5, "Tomorrow: morning light walk."),
      day(7, "Walk in the morning light", "The season's gift",
        "Walk slowly in the early light for 10 minutes.", 10, "Beautifully done 🌿"),
    ],
  },

  busy_lifestyle: {
    id: "busy_lifestyle",
    name: "Busy Lifestyle",
    emoji: "💧",
    tagline: "Five-minute Satvic.",
    rationale:
      "Made for the calendar-full days. Nothing here takes more than 5 minutes.",
    emotional_tone: "Practical, low-commitment.",
    starter_badge: "hydration_hero",
    starter_plant: "coconut",
    example_notification: "Busy day? One fruit + soaked almonds is a full Satvic breakfast.",
    days: [
      day(1, "Carry a water bottle all day", "Hydration is the easiest win",
        "Refill twice — that's the day's goal.", 2, "Tomorrow: soak almonds tonight."),
      day(2, "Soak 5 almonds tonight", "2 minutes, big payoff",
        "Drop them in water before bed.", 2, "Tomorrow: eat them with one fruit."),
      day(3, "Fruit + soaked almonds breakfast", "A 5-minute Satvic breakfast",
        "Two ingredients. That's it.", 5, "Tomorrow: warm water in the office."),
      day(4, "Warm water at your desk", "Switch one cup",
        "Replace one cold/coffee cup with warm water today.", 2, "Tomorrow: a fruit before lunch."),
      day(5, "A fruit 20 min before lunch", "A small ritual at lunch",
        "Even at the desk — works the same.", 5, "Tomorrow: a 10-minute walk."),
      day(6, "10-minute walk anytime", "Walking is the practice",
        "Stairs, lunch loop, after-dinner — any 10 minutes.", 10, "Tomorrow: light dinner."),
      day(7, "Light dinner before 8 pm", "Earlier is doable",
        "Aim before 8 pm if 7:30 feels hard.", 15, "Beautifully done — even on a busy week 🌿"),
    ],
  },

  deep_practice: {
    id: "deep_practice",
    name: "Deep Satvic Practice",
    emoji: "🌳",
    tagline: "Go a little deeper.",
    rationale: "For those already on the path, ready to deepen rhythm and reflection.",
    emotional_tone: "Reflective, layered.",
    starter_badge: "sangha_seedling",
    starter_plant: "lotus",
    example_notification: "This week's deep dive: how food combinations affect digestion.",
    days: [
      day(1, "Mindful chewing meditation at one meal", "Eating as practice",
        "Slow, quiet, present — one meal, full attention.", 20, "Tomorrow: food combining."),
      day(2, "Food combining experiment", "Pair gently",
        "Notice how fruits + grains feel vs fruits alone.", 15, "Tomorrow: morning journal."),
      day(3, "Morning journaling for 5 minutes", "Reflection deepens habit",
        "Three lines is enough. What did your body say yesterday?", 5, "Tomorrow: oil pulling experiment.",
        "mindful_journaling_prompt"),
      day(4, "Oil pulling for 5 minutes", "A morning ritual",
        "Five minutes of coconut oil swishing on rising.", 5, "Tomorrow: silence at one meal."),
      day(5, "Silent meal", "Eating without screens or speech",
        "One meal in silence. Listen to the food.", 20, "Tomorrow: post-sunset rest."),
      day(6, "No screens after sunset for one hour", "A wind-down ritual",
        "Sit with tea, read, or simply rest.", 60, "Tomorrow: a seva offering."),
      day(7, "A small act of seva today", "Share the practice",
        "Cook for someone. Send a recipe. Plant a Family Tree.", 30, "Beautifully done 🌳"),
    ],
  },
};

export function assignPath(answers: QuizAnswers): PathId {
  const g = answers.goal;
  if (g === "digestion") return "digestion_support";
  if (g === "weight_balance") return "weight_balance";
  if (g === "family") return "family_satvic";
  if (g === "seasonal") return "seasonal_wellness";
  if (g === "deep_practice") return "deep_practice";
  if (answers.time_minutes === 5 || answers.struggle === "info_overload") return "busy_lifestyle";
  return "gentle_beginner";
}

export const PATH_LIST = Object.values(PATHS);
